# Configurations
title:            Blog
longtitle:        Marchant's Blog
author:           Eamon Marchant
email:            eamonmarchant@gmail.com
description: >
  Quick thoughts, probably related to STEM stuff.

version:          1.0
gitbook_version:  3.2.3

url:              'https://mremarchant.github.io'
baseurl:          '/projects/Writing'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook


# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     mremarchant/mremarchant.github.io/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - posts


page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji